### ISSUE TITLE
TODO: Game Data Additions

### ISSUE THREAD

**Issue by CatClawed** [CatClawed/barrelwisdom#4]
Games made from Firis onward have higher priority because they're easier to do. PhyreEngine (Rorona, Meruru, Ayesha) games are dead last because they're the hardest.

- [ ] Rorona
- [x] Totori
- [ ] Meruru
- [ ] Ayesha
- [x] Escha & Logy
- [x] Shallie
- [ ] Sophie
- [x] Firis
- [ ] Lydie & Suelle (in progress)
- [ ] Lulua
- [ ] Ryza 1 (in progress)
- [x] Ryza 2
- [x] Sophie 2
- [ ] Ryza 3 (lol in progress)
- [x] Resleriana (forever in progress)
- [x] Blue Reflection
- [x] Blue Reflection Second Light

Maybe eventually
* Annie
* Nelke

Probably never:
* Nights of Azure
* Nights of Azure 2
